#!/usr/bin/env python3
"""Registry of tag options per domain and category.

Subset extracted from docs/Briefs_et_tags.txt. Extend as needed.

This module centralizes shared category lists so both domains can reference
the same options. The public `TAGS_REGISTRY` API remains unchanged to
preserve compatibility with existing random prompt logic.
"""

# Shared (domain-agnostic) option lists
COMMON_PLACES = [
    "Vieille Ville",
    "Léviathan pétrifié",
    "Couronnes intermédiaires",
    "Périphéries",
    "Citadelle de Daïlon",
    "Merid",
    "Désert des Echos Perdus",
    "Forêts de Corail",
    "Puits céleste",
    "Océan de Ténèbres",
    "Plaines de l'Exuvie",
    "Marché automaton",
    "Fosse aux Idoles déchues",
    "Antichambre des Impossibles",
    "Steppe des Éteignoirs",
    "Cité Labiale",
    "Tombeau des lueurs dissidentes",
    "Jungle Vivarcade",
    "Escelion",
    "Xyriad Achromatique",
    "Ciel de Roche",
    "Océan mécanique",
    "Autre lieu (à inventer)",
]

COMMON_SPECIES = [
    "Van'Doei",
    "Cen'Doei",
    "Qadul'Doei",
    "Rash'Doei",
    "Aedres",
    "Imuins",
    "Vaideccans",
    "Humains",
    "Rêveurs primordiaux",
    "Seigneurs Originels",
    "Aberrations Bouffies",
    "Moribandons",
    "Umcut",
    "Railleurs",
    "Vohars",
    "Kephrasites",
    "Construits",
    "Autre espèce (à inventer)",
]

COMMON_FACTIONS = [
    "Culte de l'Anentropie",
    "Barvasinkul",
    "Murmurateurs",
    "Symbiotisme",
    "Paradigme Ésothrope",
    "Aldravinds",
    "Indépendant/Paria",
    "Autre faction (à inventer)",
]

TAGS_REGISTRY = {
    "Personnages": {
        "TYPE": [
            "PJ (Personnage Joueur)",
            "PNJ principal",
            "PNJ recrutable",
            "PNJ secondaire",
            "PNJ historique",
            "Entité supérieure",
        ],
        "GENRE": [
            "Féminin",
            "Masculin",
            "Non défini",
            "Non Binaire",
            "Pluriel",
        ],
        "CATÉGORIE_ÂGE": [
            "Enfant",
            "Adolescent",
            "Jeune adulte",
            "Adulte",
            "Âge mûr",
            "Vénérable",
            "Ancestral",
        ],
        "ESPÈCE": COMMON_SPECIES,
        "LIEU": COMMON_PLACES,
        "ORIGINE": COMMON_PLACES,
        "APPARENCE": [
            "Émaciée",
            "Imposante",
            "Délicate",
            "Commune",
        ],
        "OCCUPATION": [
            "Artisan",
            "Guerrier/Combattant",
            "Érudit/Chercheur",
            "Prêtre/Exégète",
            "Marchand",
            "Cartographe",
            "Archiviste",
            "Thaumaturge",
            "Courtisan",
            "Esclave",
            "Paria/Exilé",
            "Garde/Soldat",
            "Artiste",
            "Guérisseur",
            "Espion",
            "Prophète",
            "Architecte",
            "Alchimiste",
            "Diplomate",
            "Sans occupation",
            "Autre occupation (à inventer)",
        ],
        "FACTION": COMMON_FACTIONS,
        "ÉTAT_SANTÉ": [
            "Valide",
            "Handicap physique",
            "Handicap sensoriel",
            "Maladie chronique",
            "Condition mentale",
            "Mourant/Affaibli",
        ],
        "CLASSE_SOCIALE": [
            "Privilégié",
            "Classe moyenne",
            "Précaire",
            "Miséreux",
            "Paria",
        ],
        "ÉDUCATION": [
            "Aucune (analphabète)",
            "Faible (autodidacte)",
            "Moyenne (éducation classique)",
            "Importante (intellectuelle)",
            "Avancée (érudit)",
        ],
        "STATUT_SOCIAL": [
            "Respecté",
            "Neutre",
            "Craint",
            "Méprisé",
            "Stigmatisé",
        ],
        "QUALITÉS": [
            "Confiante",
            "Conciliante",
            "Courageuse",
            "Décent",
            "Détachée",
            "Diplomate",
            "Discrète",
            "Empathique",
            "Energique",
            "Fiable",
            "Généreuse",
            "Honnête",
            "Humble",
            "Ingénieuse",
            "Lucide",
            "Idéaliste",
            "Loyale",
            "Modeste",
            "Organisée",
            "Ouverte",
            "Patiente",
            "Persévérante",
            "Posée",
            "Prudente",
            "Rigoureuse",
            "Respectueuse",
            "Responsable",
            "Sincère",
            "Tempérée",
            "Tolérante",
        ],
        "DÉFAUTS": [
            "Autoritaire",
            "Colérique",
            "Cynique",
            "Manipulatrice",
            "Obstinée",
            "Désordonnée",
            "Égoïste",
            "Incompétent",
            "Provocatrice",
            "Prétentieuse",
            "Insensible",
            "Défaitiste",
            "Irresponsable",
            "Intolérante",
            "Indiscrète",
            "Imprudente",
            "Irrespectueuse",
            "Impatiente",
            "Instable",
            "Lâche",
            "Malhonnête",
            "Méfiante",
            "Naïve",
            "Négligente",
            "Orgueilleuse",
            "Paresseuse",
            "Sensuelle",
            "Susceptible",
            "Traîtresse",
        ],
        "FAIBLESSE": [
            "Obsession",
            "Traumatisme non résolu",
            "Dépendance",
            "Attachement toxique",
            "Orgueil démesuré",
            "Peur paralysante",
            "Dissociation",
            "Rigidité mentale",
            "Autre faiblesse (à inventer)",
        ],
        "DÉSIR": [
            "Pouvoir",
            "Connaissance",
            "Vengeance",
            "Rédemption",
            "Liberté",
            "Reconnaissance",
            "Préservation",
            "Transformation",
            "Connexion",
            "Destruction",
            "Autre désir (à inventer)",
        ],
        "BESOIN": [
            "Acceptation",
            "Lâcher-prise",
            "Connexion authentique",
            "Pardon",
            "Vulnérabilité",
            "Sens",
            "Confrontation",
            "Changement",
            "Autre besoin (à inventer)",
        ],
        "AXE_IDÉOLOGIQUE": [
            "Retrait",
            "Rébellion",
            "Destruction",
            "Subversion",
            "Connexion",
            "Contrôle",
        ],
        "ARCHÉTYPE": [
            "Artiste / Cynique",
            "Amoureuse / Faire-valoir",
            "Magicienne / Sorcier",
            "Rebelle / Destructeur",
            "Guerrière / Surhomme",
            "Friponne / Menteur",
            "Mentor / Gourou",
            "Reine / Tyran",
        ],
        "REGISTRE_LANGUE": [
            "Abraldique ancien",
            "Principit",
            "Kesh-Varash",
            "Néo-Frémissant",
            "Langage vertébral",
            "Mécanaqueux",
            "Acqueux",
            "Abyssal",
            "Commun",
            "Autre registre (à inventer)",
        ],
        "POSTURE_MORALE": [
            "Résiste activement",
            "Subvertit de l'intérieur",
            "Relativise/Philosophe",
            "Accepte/S'adapte",
            "Fait partie de l'oppression",
            "Se retire/Fuit",
        ],
    },
    "Lieux": {
        "RÔLE": [
            "Ville",
            "Lieu unique",
            "Lieu militaire",
            "Lieu de culte",
            "Zone magique",
            "Zone naturelle",
            "Lieu commercial",
            "Lieu artisanal",
        ],
        "TAILLE": [
            "Monde",
            "Pays",
            "Région",
            "District",
            "Secteur",
            "Site",
            "Point d'intérêt",
        ],
        "LIEU": COMMON_PLACES,
        "ESPÈCE": COMMON_SPECIES,
        "ATMOSPHÈRE": [
            "Oppressante",
            "Paisible",
            "Chaotique",
            "Sacrée",
            "Abandonnée",
            "Vivante/Grouillante",
            "Mélancolique",
            "Inquiétante",
            "Émerveillement",
        ],
        "PARTICULARITÉ": [
            "Bioluminescence",
            "Échos mémoriels",
            "Anomalie spatiale",
            "Conscience résiduelle",
            "Aucune",
        ],
        "APPARENCE_LIEU": [
            "Ruines anciennes",
            "Architecture organique",
            "Structure géométrique",
            "Formation naturelle",
            "Hybride (nature/architecture)",
            "Minérale/Cristalline",
            "Osseuse/Fossile",
            "Mécanique",
            "Éthérée/Immatérielle",
        ],
        "ACCESSIBILITÉ": [
            "Ouvert à tous",
            "Accès restreint",
            "Secret/Caché",
            "Dangereux d'accès",
            "Inaccessible sans aide",
        ],
        "DANGER": [
            "Sûr",
            "Risques mineurs",
            "Dangereux",
            "Mortel",
            "Variable/Imprévisible",
        ],
        "LOIS_PHYSIQUES": [
            "Stables (comme ailleurs)",
            "Légèrement altérées",
            "Fortement altérées",
            "Incompatibles (zone limitrophe)",
            "Instables/Variables",
        ],
        "FONCTION_NARRATIVE": [
            "Refuge/Base",
            "Lieu de confrontation",
            "Source de mystère",
            "Objectif à atteindre",
            "Passage obligé",
            "Zone d'exploration libre",
            "Lieu de révélation",
        ],
        "FACTION": COMMON_FACTIONS,
    },
}



